In [1]:
import numpy as np
import pandas as pd
import torch


from MultiLabelPFN.src.tabicl.prior.dataset import SCMPrior

In [2]:
pds = SCMPrior(batch_size=20, max_classes=3)

test1 = pds.get_batch()
#test2 = pds.get_batch(num_outputs=3)
#print(test)

In [8]:
print(test1[5])
#print(test1[1][19])

#print(test2[0][19])
#print(test2[1][19])

IndexError: tuple index out of range

In [23]:
test3 = torch.Tensor([[0.2, 0.6, 0.4],
              [0.0, 0.1, 0.2],
              [0.3, 0.2, 0.0]])
test4 = torch.Tensor([0.5, 0.6, 0.4])

input = test3

#print(test3[:,0])

if input.ndim == 1:
    input = input.unsqueeze(-1)

labels = torch.zeros_like(input)

print(labels)

for i in range(input.shape[1]):
    tmp_input = input[:,i]

    classes = tmp_input

    labels[:,i] = classes


print(labels)


'''
for i in range(1):
    print("hi")


print(test4.ndim)
print((input > torch.median(input, 0)[0]).float())'''

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.2000, 0.6000, 0.4000],
        [0.0000, 0.1000, 0.2000],
        [0.3000, 0.2000, 0.0000]])


'\nfor i in range(1):\n    print("hi")\n\n\nprint(test4.ndim)\nprint((input > torch.median(input, 0)[0]).float())'

In [25]:
y = test3

unique_vals, _ = torch.unique(y, return_inverse=True)
indices = unique_vals.argsort()
print(indices[torch.searchsorted(unique_vals, y)])

tensor([[2, 5, 4],
        [0, 1, 2],
        [3, 2, 0]])
