In [1]:
import numpy as np
import pandas as pd
import torch


from MultiLabelPFN.src.tabicl.prior.dataset import SCMPrior

In [6]:
pds = SCMPrior(batch_size=5, max_labels=3)

test1 = pds.get_batch()
#test2 = pds.get_batch(num_outputs=3)
#print(test)
print(test1[1][0,:,:])


tensor([[0., 0., 0.],
        [1., 0., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


In [18]:
print(test1[1][0,:,2].unique())

#print(test1[1][19])

#print(test2[0][19])
#print(test2[1][19])

tensor([0., 1.])


In [28]:
test3 = torch.Tensor([[0.2, 0.6, 0.4],
              [0.9, 0.1, 0.2],
              [0.3, 0.2, 0.0]])
test4 = torch.Tensor([[0.5],
                     [0.6],
                     [0.4]])

test5 = torch.randn((10,3))

input=test3

#input = test3
print(torch.median(input, 0)[0])
print((input > torch.median(input, 0)[0]).float())



tensor([0.3000, 0.2000, 0.2000])
tensor([[0., 1., 1.],
        [1., 0., 0.],
        [0., 0., 0.]])


In [111]:
import random
#test5 = torch.randn((10,3))

#input=test5
#quan = random.uniform(0.5, 0.9)
quan = torch.zeros(input.shape[1]).uniform_(0.5, 0.9)
print(quan)
print(torch.quantile(input, quan, dim=0))
print(torch.diagonal(torch.quantile(input, quan, dim=0)))

print((input > torch.quantile(input, quan, dim=0)).float())



tensor([0.8565, 0.6126, 0.7583])
tensor([[0.7277, 0.4852, 0.3426],
        [0.4351, 0.2901, 0.2450],
        [0.6100, 0.4066, 0.3033]])
tensor([0.7277, 0.2901, 0.3033])
tensor([[0., 1., 1.],
        [1., 0., 0.],
        [0., 0., 0.]])


In [97]:
print(torch.zeros(input.shape[1]).uniform_(0.5, 0.9))



tensor([0.5340, 0.7543, 0.6386])
