In [1]:
import numpy as np
import pandas as pd
import torch


from MultiLabelPFN.src.tabicl.prior.dataset import SCMPrior

In [6]:
pds = SCMPrior(batch_size=5, max_labels=3)

test1 = pds.get_batch()
#test2 = pds.get_batch(num_outputs=3)
#print(test)
print(test1[1][0,:,:])


tensor([[0., 0., 0.],
        [1., 0., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


In [18]:
print(test1[1][0,:,2].unique())

#print(test1[1][19])

#print(test2[0][19])
#print(test2[1][19])

tensor([0., 1.])


In [28]:
test3 = torch.Tensor([[0.2, 0.6, 0.4],
              [0.9, 0.1, 0.2],
              [0.3, 0.2, 0.0]])
test4 = torch.Tensor([[0.5],
                     [0.6],
                     [0.4]])

test5 = torch.randn((10,3))

input=test3

#input = test3
print(torch.median(input, 0)[0])
print((input > torch.median(input, 0)[0]).float())



tensor([0.3000, 0.2000, 0.2000])
tensor([[0., 1., 1.],
        [1., 0., 0.],
        [0., 0., 0.]])


In [111]:
import random
#test5 = torch.randn((10,3))

#input=test5
#quan = random.uniform(0.5, 0.9)
quan = torch.zeros(input.shape[1]).uniform_(0.5, 0.9)
print(quan)
print(torch.quantile(input, quan, dim=0))
print(torch.diagonal(torch.quantile(input, quan, dim=0)))

print((input > torch.quantile(input, quan, dim=0)).float())



tensor([0.8565, 0.6126, 0.7583])
tensor([[0.7277, 0.4852, 0.3426],
        [0.4351, 0.2901, 0.2450],
        [0.6100, 0.4066, 0.3033]])
tensor([0.7277, 0.2901, 0.3033])
tensor([[0., 1., 1.],
        [1., 0., 0.],
        [0., 0., 0.]])


In [97]:
print(torch.zeros(input.shape[1]).uniform_(0.5, 0.9))



tensor([0.5340, 0.7543, 0.6386])


In [1]:
with open("./test.txt", "w") as f:
    f.write("test")

In [45]:
import torch
import torch.nn.functional as F

# Set reproducibility
torch.manual_seed(42)

# Simulate data
B, E, L = 2, 3, 4  # mini_batch, examples, labels

# Random logits and targets
logits = torch.randn(B, E, L)
targets = torch.randint(0, 1, (B, E, L)).float()

# Compute BCE with logits normally
loss_unflattened = F.binary_cross_entropy_with_logits(logits, targets)

# Flatten both tensors
loss_flattened = F.binary_cross_entropy_with_logits(
    logits.flatten(end_dim=-3), targets.flatten(end_dim=-3)
)

print("Loss (unflattened):", loss_unflattened.item())
print("Loss (flattened):  ", loss_flattened.item())
print("Difference:", abs(loss_unflattened.item() - loss_flattened.item()))


Loss (unflattened): 0.6923484802246094
Loss (flattened):   0.6923484802246094
Difference: 0.0


In [5]:
print(logits.shape)

torch.Size([2, 3, 4])


In [12]:
import torch
import torch.nn.functional as F

# Set reproducibility
torch.manual_seed(42)

# Simulate data
B, E, L = 2, 3, 4  # mini_batch, examples, labels

# Random logits and targets
logits = torch.randn(B, E, L)
logits2 = torch.randn(B, E)
targets = torch.randint(0, 2, (B, E, L)).float()


print(logits.argmax(dim=1).shape)
print(logits2.argmax(dim=1).shape)
print(targets)

torch.Size([2, 4])
torch.Size([2])
tensor([[[0., 1., 0., 1.],
         [1., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 1., 1., 0.],
         [1., 1., 1., 1.],
         [0., 1., 0., 1.]]])


In [18]:
from tabicl.prior.dataset import PriorDataset

pds = PriorDataset()

X, y2, d, i, t = pds.get_batch()

In [20]:
print(y2.long().flatten().shape)

torch.Size([262144])


In [16]:
from MultiLabelPFN.src.tabicl.prior.dataset import PriorDataset

pds = PriorDataset()

X, y, d, i, t = pds.get_batch()

In [22]:
print(y.shape)

torch.Size([256, 1024, 10])


In [51]:
logits = torch.randn(256, 1024, 10)

In [54]:
print((((logits.flatten(end_dim=-2) > 0).float() == y.flatten(end_dim=-2)).sum(dim=-1) / y.shape[-1]).sum() / y.flatten(end_dim=-2).shape[-2])

tensor(0.4999)


In [43]:
y.flatten(end_dim=-2).shape

torch.Size([262144, 10])

In [8]:
test6 = np.array([[0.2, 0.3, 0.6],
                 [0.7, 0.3, 0.6],
                 [0.2, 0.4, 0.3]])

print((test6 > 0.5).astype(int))

[[0 0 1]
 [1 0 1]
 [0 0 0]]


In [5]:
import torch

new = torch.randn(1, 4, 4)

print(torch.nn.functional.pad(new, (0,2)).shape)

torch.Size([1, 4, 6])
